# Generated by Django 3.1 on 2020-08-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20200821_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorrecords',
            name='totals',
            field=models.IntegerField(blank=True, default=0.0, null=True),
        ),
    ]
